sudo: required
# https://docs.travis-ci.com/user/trusty-ci-environment/
dist: trusty
language: python
python:
    # python versions used in el7 SCL & supported fedora
    - "3.5"
    - "3.6"
install: source .travis/install.sh
script: source .travis/script.sh
